apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "win0bot-helm.fullname" . }}
  labels:
    {{- include "win0bot-helm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "win0bot-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "win0bot-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "win0bot-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- if not .Values.postgresql.enabled}}
            - name: DATABASE_URL
              value: {{ .Values.win0bot.databaseUrl | quote }}
          {{- end }}
            - name: admins
              value: {{ .Values.win0bot.admins | quote }}
            - name: discordToken
              value: {{ .Values.win0bot.discordToken | quote }}
            - name: effectiveRoles
              value: {{ .Values.win0bot.effectiveRoles | quote }}
            - name: mods
              value: {{ .Values.win0bot.mods | quote }}
            - name: prefix
              value: {{ .Values.win0bot.prefix | quote }}
            - name: telegramToken
              value: {{ .Values.win0bot.telegramToken | quote }}
            - name: voiceChannleJoinMsg
              value: {{ .Values.win0bot.voiceChannleJoinMsg | quote }}
            - name: voiceTextChnList
              value: {{ .Values.win0bot.voiceTextChnList | quote }}
            {{- if .Values.postgresql.enabled}}
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "call-nested" (list . "postgresql" "postgresql.secretName") }}
                  key: postgresql-password
            - name: POSTGRES_USER
              value: {{ include "call-nested" (list . "postgresql" "postgresql.username") }}
            - name: POSTGRESQL_PORT_NUMBER
              value: {{ .Values.postgresql.containerPorts.postgresql | quote }}
            - name: POSTGRESQL_URL
              value: {{ include "call-nested" (list . "postgresql" "common.names.fullname") }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      volumeMounts:
      {{- if .Values.persistentvolumeclaim.enabled}}
        - {{ include "win0bot-helm.fullname" . }}-data
          mountPath: /app
      {{- end }}
      {{- end }}
