{{- if .Values.persistentvolumeclaim.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "win0bot-helm.fullname" . }}-data
  labels:
    {{- include "win0bot-helm.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentvolumeclaim.size }}
  storageClassName: {{ .Values.persistentvolumeclaim.storageClassName }}
  volumeMode: Filesystem
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
{{- end }}